# .github/workflows/deploy.yml

name: Stipendivm

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  heroku-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Deploy to Heroku
      uses: akhileshns/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
        heroku_email: ${{ secrets.HEROKU_EMAIL }}
        justlogin: true
        usedocker: true
      env:
          NODE_ENV: production
          STRIPE_PUBLISHABLE_KEY: ${{ secrets.STRIPE_PUBLISHABLE_KEY }}
          STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
          STRIPE_SHOPPING_CART_WEBHOOK_SECRET: ${{ secrets.STRIPE_SHOPPING_CART_WEBHOOK_SECRET }}
          STRIPE_ACCOUNT_COUNTRY: ${{ secrets.STRIPE_ACCOUNT_COUNTRY }}
          PAYMENT_METHODS: ${{ secrets.PAYMENT_METHODS }}
